/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : test.g
 *     -                            On : 2019-12-03 21:07:06
 *     -                for the parser : testParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */

    #include <assert.h>

/* End of Header action.
 * =============================================================================
 */

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "testParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   ptestParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  ptestParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->ptestParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->ptestParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO
#undef		DBG

#define	    PARSER				ctx->pParser
#define	    RECOGNIZER				PARSER->rec
#define	    PSRSTATE				RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)			RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT				PARSER->tstream
#define	    STRSTREAM				INPUT
#define	    ISTREAM				INPUT->istream
#define	    INDEX()				ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()			(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				PSRSTATE->exception
#define	    MATCHT(t, fs)			RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()				RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK				PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define	    FOLLOWPUSH(x)
#define	    FOLLOWPOP()
#else
#define	    FOLLOWPUSH(x)			FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()				FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define	    PRECOVER()				RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()			RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)				INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)				INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()				ISTREAM->consume(ISTREAM)
#define	    MARK()				ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define	    SEEK(n)				ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY			PSRSTATE->errorRecovery
#define	    FAILEDFLAG				PSRSTATE->failed
#define	    HASFAILED()				(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING			PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   testParserTokenNames[18+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "ASSIGN",
        (pANTLR3_UINT8) "BLOCK",
        (pANTLR3_UINT8) "DEF",
        (pANTLR3_UINT8) "DIV",
        (pANTLR3_UINT8) "ID",
        (pANTLR3_UINT8) "INT",
        (pANTLR3_UINT8) "MINUS",
        (pANTLR3_UINT8) "NEWLINE",
        (pANTLR3_UINT8) "PLUS",
        (pANTLR3_UINT8) "PRINT",
        (pANTLR3_UINT8) "TIMES",
        (pANTLR3_UINT8) "WS",
        (pANTLR3_UINT8) "'('",
        (pANTLR3_UINT8) "')'",
        (pANTLR3_UINT8) "','",
        (pANTLR3_UINT8) "';'",
        (pANTLR3_UINT8) "'{'",
        (pANTLR3_UINT8) "'}'"
       };



// Forward declare the locally static matching functions we have generated.
//
static 
 testParser_expr_return
	expr    (ptestParser ctx);
static 
 testParser_multExpr_return
	multExpr    (ptestParser ctx);
static 
 testParser_atom_return
	atom    (ptestParser ctx);
static 
 testParser_stmt_return
	stmt    (ptestParser ctx);
static 
 testParser_print_stmt_return
	print_stmt    (ptestParser ctx);
static 
 testParser_def_stmt_return
	def_stmt    (ptestParser ctx);
static 
 testParser_def_id_return
	def_id    (ptestParser ctx);
static 
 testParser_block_code_return
	block_code    (ptestParser ctx);
static 
 testParser_blocks_return
	blocks    (ptestParser ctx);
static 
 testParser_prog_return
	prog    (ptestParser ctx);
static void	testParserFree(ptestParser ctx);
static void     testParserReset (ptestParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "test.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new testParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API ptestParser
testParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return testParserNewSSD(instream, NULL);
}

/** \brief Create a new testParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API ptestParser
testParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    ptestParser ctx;	    /* Context structure we will build and return   */

    ctx	= (ptestParser) ANTLR3_CALLOC(1, sizeof(testParser));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in testParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our testParser interface
     */
    ctx->expr	= expr;
    ctx->multExpr	= multExpr;
    ctx->atom	= atom;
    ctx->stmt	= stmt;
    ctx->print_stmt	= print_stmt;
    ctx->def_stmt	= def_stmt;
    ctx->def_id	= def_id;
    ctx->block_code	= block_code;
    ctx->blocks	= blocks;
    ctx->prog	= prog;
    ctx->free			= testParserFree;
    ctx->reset			= testParserReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */
ADAPTOR	= ANTLR3_TREE_ADAPTORNew(instream->tstream->tokenSource->strFactory);

ctx->vectors	= antlr3VectorFactoryNew(0);
    /* Install the token table
     */
    PSRSTATE->tokenNames   = testParserTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
testParserReset (ptestParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 testParserFree(ptestParser ctx)
 {
    /* Free any scope memory
     */

ctx->vectors->close(ctx->vectors);
/* We created the adaptor so we must free it
 */
ADAPTOR->free(ADAPTOR);
	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);


    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return testParserTokenNames;
}


/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_multExpr_in_expr54  */
static	ANTLR3_BITWORD FOLLOW_multExpr_in_expr54_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001402) };
static  ANTLR3_BITSET_LIST FOLLOW_multExpr_in_expr54	= { FOLLOW_multExpr_in_expr54_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PLUS_in_expr58  */
static	ANTLR3_BITWORD FOLLOW_PLUS_in_expr58_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010300) };
static  ANTLR3_BITSET_LIST FOLLOW_PLUS_in_expr58	= { FOLLOW_PLUS_in_expr58_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_MINUS_in_expr63  */
static	ANTLR3_BITWORD FOLLOW_MINUS_in_expr63_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010300) };
static  ANTLR3_BITSET_LIST FOLLOW_MINUS_in_expr63	= { FOLLOW_MINUS_in_expr63_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_multExpr_in_expr67  */
static	ANTLR3_BITWORD FOLLOW_multExpr_in_expr67_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001402) };
static  ANTLR3_BITSET_LIST FOLLOW_multExpr_in_expr67	= { FOLLOW_multExpr_in_expr67_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_atom_in_multExpr100  */
static	ANTLR3_BITWORD FOLLOW_atom_in_multExpr100_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004082) };
static  ANTLR3_BITSET_LIST FOLLOW_atom_in_multExpr100	= { FOLLOW_atom_in_multExpr100_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_TIMES_in_multExpr104  */
static	ANTLR3_BITWORD FOLLOW_TIMES_in_multExpr104_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010300) };
static  ANTLR3_BITSET_LIST FOLLOW_TIMES_in_multExpr104	= { FOLLOW_TIMES_in_multExpr104_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_DIV_in_multExpr109  */
static	ANTLR3_BITWORD FOLLOW_DIV_in_multExpr109_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010300) };
static  ANTLR3_BITSET_LIST FOLLOW_DIV_in_multExpr109	= { FOLLOW_DIV_in_multExpr109_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_atom_in_multExpr113  */
static	ANTLR3_BITWORD FOLLOW_atom_in_multExpr113_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004082) };
static  ANTLR3_BITSET_LIST FOLLOW_atom_in_multExpr113	= { FOLLOW_atom_in_multExpr113_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_INT_in_atom140  */
static	ANTLR3_BITWORD FOLLOW_INT_in_atom140_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_INT_in_atom140	= { FOLLOW_INT_in_atom140_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_atom148  */
static	ANTLR3_BITWORD FOLLOW_ID_in_atom148_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_atom148	= { FOLLOW_ID_in_atom148_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_16_in_atom156  */
static	ANTLR3_BITWORD FOLLOW_16_in_atom156_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010300) };
static  ANTLR3_BITSET_LIST FOLLOW_16_in_atom156	= { FOLLOW_16_in_atom156_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_atom159  */
static	ANTLR3_BITWORD FOLLOW_expr_in_atom159_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_atom159	= { FOLLOW_expr_in_atom159_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_17_in_atom161  */
static	ANTLR3_BITWORD FOLLOW_17_in_atom161_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_17_in_atom161	= { FOLLOW_17_in_atom161_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_stmt181  */
static	ANTLR3_BITWORD FOLLOW_expr_in_stmt181_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000080000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_stmt181	= { FOLLOW_expr_in_stmt181_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_19_in_stmt183  */
static	ANTLR3_BITWORD FOLLOW_19_in_stmt183_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000800) };
static  ANTLR3_BITSET_LIST FOLLOW_19_in_stmt183	= { FOLLOW_19_in_stmt183_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_stmt185  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_stmt185_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_stmt185	= { FOLLOW_NEWLINE_in_stmt185_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_stmt198  */
static	ANTLR3_BITWORD FOLLOW_ID_in_stmt198_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_stmt198	= { FOLLOW_ID_in_stmt198_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ASSIGN_in_stmt200  */
static	ANTLR3_BITWORD FOLLOW_ASSIGN_in_stmt200_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010300) };
static  ANTLR3_BITSET_LIST FOLLOW_ASSIGN_in_stmt200	= { FOLLOW_ASSIGN_in_stmt200_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_stmt202  */
static	ANTLR3_BITWORD FOLLOW_expr_in_stmt202_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000080000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_stmt202	= { FOLLOW_expr_in_stmt202_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_19_in_stmt204  */
static	ANTLR3_BITWORD FOLLOW_19_in_stmt204_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000800) };
static  ANTLR3_BITSET_LIST FOLLOW_19_in_stmt204	= { FOLLOW_19_in_stmt204_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_stmt206  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_stmt206_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_stmt206	= { FOLLOW_NEWLINE_in_stmt206_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_19_in_stmt224  */
static	ANTLR3_BITWORD FOLLOW_19_in_stmt224_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000080800) };
static  ANTLR3_BITSET_LIST FOLLOW_19_in_stmt224	= { FOLLOW_19_in_stmt224_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_stmt227  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_stmt227_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_stmt227	= { FOLLOW_NEWLINE_in_stmt227_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_def_stmt_in_stmt238  */
static	ANTLR3_BITWORD FOLLOW_def_stmt_in_stmt238_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_def_stmt_in_stmt238	= { FOLLOW_def_stmt_in_stmt238_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_print_stmt_in_stmt246  */
static	ANTLR3_BITWORD FOLLOW_print_stmt_in_stmt246_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_print_stmt_in_stmt246	= { FOLLOW_print_stmt_in_stmt246_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_blocks_in_stmt254  */
static	ANTLR3_BITWORD FOLLOW_blocks_in_stmt254_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_blocks_in_stmt254	= { FOLLOW_blocks_in_stmt254_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PRINT_in_print_stmt266  */
static	ANTLR3_BITWORD FOLLOW_PRINT_in_print_stmt266_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010300) };
static  ANTLR3_BITSET_LIST FOLLOW_PRINT_in_print_stmt266	= { FOLLOW_PRINT_in_print_stmt266_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_print_stmt269  */
static	ANTLR3_BITWORD FOLLOW_expr_in_print_stmt269_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000080000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_print_stmt269	= { FOLLOW_expr_in_print_stmt269_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_19_in_print_stmt271  */
static	ANTLR3_BITWORD FOLLOW_19_in_print_stmt271_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_19_in_print_stmt271	= { FOLLOW_19_in_print_stmt271_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_DEF_in_def_stmt278  */
static	ANTLR3_BITWORD FOLLOW_DEF_in_def_stmt278_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_DEF_in_def_stmt278	= { FOLLOW_DEF_in_def_stmt278_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_def_id_in_def_stmt281  */
static	ANTLR3_BITWORD FOLLOW_def_id_in_def_stmt281_bits[]	= { ANTLR3_UINT64_LIT(0x00000000000C0000) };
static  ANTLR3_BITSET_LIST FOLLOW_def_id_in_def_stmt281	= { FOLLOW_def_id_in_def_stmt281_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_18_in_def_stmt284  */
static	ANTLR3_BITWORD FOLLOW_18_in_def_stmt284_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_18_in_def_stmt284	= { FOLLOW_18_in_def_stmt284_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_def_id_in_def_stmt287  */
static	ANTLR3_BITWORD FOLLOW_def_id_in_def_stmt287_bits[]	= { ANTLR3_UINT64_LIT(0x00000000000C0000) };
static  ANTLR3_BITSET_LIST FOLLOW_def_id_in_def_stmt287	= { FOLLOW_def_id_in_def_stmt287_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_19_in_def_stmt291  */
static	ANTLR3_BITWORD FOLLOW_19_in_def_stmt291_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_19_in_def_stmt291	= { FOLLOW_19_in_def_stmt291_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_def_id298  */
static	ANTLR3_BITWORD FOLLOW_ID_in_def_id298_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000012) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_def_id298	= { FOLLOW_ID_in_def_id298_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ASSIGN_in_def_id302  */
static	ANTLR3_BITWORD FOLLOW_ASSIGN_in_def_id302_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010300) };
static  ANTLR3_BITSET_LIST FOLLOW_ASSIGN_in_def_id302	= { FOLLOW_ASSIGN_in_def_id302_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_def_id305  */
static	ANTLR3_BITWORD FOLLOW_expr_in_def_id305_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_def_id305	= { FOLLOW_expr_in_def_id305_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_stmt_in_block_code327  */
static	ANTLR3_BITWORD FOLLOW_stmt_in_block_code327_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000192B42) };
static  ANTLR3_BITSET_LIST FOLLOW_stmt_in_block_code327	= { FOLLOW_stmt_in_block_code327_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_20_in_blocks335  */
static	ANTLR3_BITWORD FOLLOW_20_in_blocks335_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000392B40) };
static  ANTLR3_BITSET_LIST FOLLOW_20_in_blocks335	= { FOLLOW_20_in_blocks335_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_block_code_in_blocks337  */
static	ANTLR3_BITWORD FOLLOW_block_code_in_blocks337_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000200000) };
static  ANTLR3_BITSET_LIST FOLLOW_block_code_in_blocks337	= { FOLLOW_block_code_in_blocks337_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_21_in_blocks339  */
static	ANTLR3_BITWORD FOLLOW_21_in_blocks339_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_21_in_blocks339	= { FOLLOW_21_in_blocks339_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_blocks_in_prog368  */
static	ANTLR3_BITWORD FOLLOW_blocks_in_prog368_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000100002) };
static  ANTLR3_BITSET_LIST FOLLOW_blocks_in_prog368	= { FOLLOW_blocks_in_prog368_bits, 1	};


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start expr
 * test.g:16:1: expr : multExpr ( ( PLUS ^| MINUS ^) multExpr )* ;
 */
static testParser_expr_return
expr(ptestParser ctx)
{
    testParser_expr_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    PLUS2;
    pANTLR3_COMMON_TOKEN    MINUS3;
    testParser_multExpr_return multExpr1;
    #undef	RETURN_TYPE_multExpr1
    #define	RETURN_TYPE_multExpr1 testParser_multExpr_return

    testParser_multExpr_return multExpr4;
    #undef	RETURN_TYPE_multExpr4
    #define	RETURN_TYPE_multExpr4 testParser_multExpr_return

    pANTLR3_BASE_TREE PLUS2_tree;
    pANTLR3_BASE_TREE MINUS3_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    PLUS2       = NULL;
    MINUS3       = NULL;
    multExpr1.tree = NULL;

    multExpr4.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    PLUS2_tree   = NULL;
    MINUS3_tree   = NULL;


    retval.tree  = NULL;

    {
        // test.g:16:5: ( multExpr ( ( PLUS ^| MINUS ^) multExpr )* )
        // test.g:16:7: multExpr ( ( PLUS ^| MINUS ^) multExpr )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_multExpr_in_expr54);
            multExpr1=multExpr(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleexprEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, multExpr1.tree);

            // test.g:16:16: ( ( PLUS ^| MINUS ^) multExpr )*

            for (;;)
            {
                int alt2=2;
                switch ( LA(1) )
                {
                case MINUS:
                case PLUS:
                	{
                		alt2=1;
                	}
                    break;

                }

                switch (alt2)
                {
            	case 1:
            	    // test.g:16:17: ( PLUS ^| MINUS ^) multExpr
            	    {
            	        // test.g:16:17: ( PLUS ^| MINUS ^)
            	        {
            	            int alt1=2;
            	            switch ( LA(1) )
            	            {
            	            case PLUS:
            	            	{
            	            		alt1=1;
            	            	}
            	                break;
            	            case MINUS:
            	            	{
            	            		alt1=2;
            	            	}
            	                break;

            	            default:
            	                CONSTRUCTEX();
            	                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            	                EXCEPTION->message      = (void *)"";
            	                EXCEPTION->decisionNum  = 1;
            	                EXCEPTION->state        = 0;


            	                goto ruleexprEx;

            	            }

            	            switch (alt1)
            	            {
            	        	case 1:
            	        	    // test.g:16:18: PLUS ^
            	        	    {
            	        	        PLUS2 = (pANTLR3_COMMON_TOKEN) MATCHT(PLUS, &FOLLOW_PLUS_in_expr58);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto ruleexprEx;
            	        	        }

            	        	        PLUS2_tree = 
            	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, PLUS2))
            	        	        ;
            	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, PLUS2_tree, root_0));


            	        	    }
            	        	    break;
            	        	case 2:
            	        	    // test.g:16:26: MINUS ^
            	        	    {
            	        	        MINUS3 = (pANTLR3_COMMON_TOKEN) MATCHT(MINUS, &FOLLOW_MINUS_in_expr63);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto ruleexprEx;
            	        	        }

            	        	        MINUS3_tree = 
            	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, MINUS3))
            	        	        ;
            	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, MINUS3_tree, root_0));


            	        	    }
            	        	    break;

            	            }
            	        }

            	        FOLLOWPUSH(FOLLOW_multExpr_in_expr67);
            	        multExpr4=multExpr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleexprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, multExpr4.tree);

            	    }
            	    break;

            	default:
            	    goto loop2;	/* break out of the loop */
            	    break;
                }
            }
            loop2: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleexprEx; /* Prevent compiler warnings */
    ruleexprEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end expr */

/**
 * $ANTLR start multExpr
 * test.g:22:1: multExpr : atom ( ( TIMES ^| DIV ^) atom )* ;
 */
static testParser_multExpr_return
multExpr(ptestParser ctx)
{
    testParser_multExpr_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    TIMES6;
    pANTLR3_COMMON_TOKEN    DIV7;
    testParser_atom_return atom5;
    #undef	RETURN_TYPE_atom5
    #define	RETURN_TYPE_atom5 testParser_atom_return

    testParser_atom_return atom8;
    #undef	RETURN_TYPE_atom8
    #define	RETURN_TYPE_atom8 testParser_atom_return

    pANTLR3_BASE_TREE TIMES6_tree;
    pANTLR3_BASE_TREE DIV7_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    TIMES6       = NULL;
    DIV7       = NULL;
    atom5.tree = NULL;

    atom8.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    TIMES6_tree   = NULL;
    DIV7_tree   = NULL;


    retval.tree  = NULL;

    {
        // test.g:23:5: ( atom ( ( TIMES ^| DIV ^) atom )* )
        // test.g:23:7: atom ( ( TIMES ^| DIV ^) atom )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_atom_in_multExpr100);
            atom5=atom(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulemultExprEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, atom5.tree);

            // test.g:23:12: ( ( TIMES ^| DIV ^) atom )*

            for (;;)
            {
                int alt4=2;
                switch ( LA(1) )
                {
                case DIV:
                case TIMES:
                	{
                		alt4=1;
                	}
                    break;

                }

                switch (alt4)
                {
            	case 1:
            	    // test.g:23:13: ( TIMES ^| DIV ^) atom
            	    {
            	        // test.g:23:13: ( TIMES ^| DIV ^)
            	        {
            	            int alt3=2;
            	            switch ( LA(1) )
            	            {
            	            case TIMES:
            	            	{
            	            		alt3=1;
            	            	}
            	                break;
            	            case DIV:
            	            	{
            	            		alt3=2;
            	            	}
            	                break;

            	            default:
            	                CONSTRUCTEX();
            	                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            	                EXCEPTION->message      = (void *)"";
            	                EXCEPTION->decisionNum  = 3;
            	                EXCEPTION->state        = 0;


            	                goto rulemultExprEx;

            	            }

            	            switch (alt3)
            	            {
            	        	case 1:
            	        	    // test.g:23:14: TIMES ^
            	        	    {
            	        	        TIMES6 = (pANTLR3_COMMON_TOKEN) MATCHT(TIMES, &FOLLOW_TIMES_in_multExpr104);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto rulemultExprEx;
            	        	        }

            	        	        TIMES6_tree = 
            	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, TIMES6))
            	        	        ;
            	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, TIMES6_tree, root_0));


            	        	    }
            	        	    break;
            	        	case 2:
            	        	    // test.g:23:23: DIV ^
            	        	    {
            	        	        DIV7 = (pANTLR3_COMMON_TOKEN) MATCHT(DIV, &FOLLOW_DIV_in_multExpr109);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto rulemultExprEx;
            	        	        }

            	        	        DIV7_tree = 
            	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, DIV7))
            	        	        ;
            	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, DIV7_tree, root_0));


            	        	    }
            	        	    break;

            	            }
            	        }

            	        FOLLOWPUSH(FOLLOW_atom_in_multExpr113);
            	        atom8=atom(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulemultExprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, atom8.tree);

            	    }
            	    break;

            	default:
            	    goto loop4;	/* break out of the loop */
            	    break;
                }
            }
            loop4: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto rulemultExprEx; /* Prevent compiler warnings */
    rulemultExprEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end multExpr */

/**
 * $ANTLR start atom
 * test.g:29:1: atom : ( INT | ID | '(' ! expr ')' !);
 */
static testParser_atom_return
atom(ptestParser ctx)
{
    testParser_atom_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    INT9;
    pANTLR3_COMMON_TOKEN    ID10;
    pANTLR3_COMMON_TOKEN    char_literal11;
    pANTLR3_COMMON_TOKEN    char_literal13;
    testParser_expr_return expr12;
    #undef	RETURN_TYPE_expr12
    #define	RETURN_TYPE_expr12 testParser_expr_return

    pANTLR3_BASE_TREE INT9_tree;
    pANTLR3_BASE_TREE ID10_tree;
    pANTLR3_BASE_TREE char_literal11_tree;
    pANTLR3_BASE_TREE char_literal13_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    INT9       = NULL;
    ID10       = NULL;
    char_literal11       = NULL;
    char_literal13       = NULL;
    expr12.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    INT9_tree   = NULL;
    ID10_tree   = NULL;
    char_literal11_tree   = NULL;
    char_literal13_tree   = NULL;


    retval.tree  = NULL;

    {
        {
            //  test.g:29:5: ( INT | ID | '(' ! expr ')' !)

            ANTLR3_UINT32 alt5;

            alt5=3;

            switch ( LA(1) )
            {
            case INT:
            	{
            		alt5=1;
            	}
                break;
            case ID:
            	{
            		alt5=2;
            	}
                break;
            case 16:
            	{
            		alt5=3;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 5;
                EXCEPTION->state        = 0;


                goto ruleatomEx;

            }

            switch (alt5)
            {
        	case 1:
        	    // test.g:29:7: INT
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        INT9 = (pANTLR3_COMMON_TOKEN) MATCHT(INT, &FOLLOW_INT_in_atom140);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        INT9_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, INT9));
        	        ADAPTOR->addChild(ADAPTOR, root_0, INT9_tree);


        	    }
        	    break;
        	case 2:
        	    // test.g:30:7: ID
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        ID10 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_atom148);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        ID10_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, ID10));
        	        ADAPTOR->addChild(ADAPTOR, root_0, ID10_tree);


        	    }
        	    break;
        	case 3:
        	    // test.g:31:7: '(' ! expr ')' !
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        char_literal11 = (pANTLR3_COMMON_TOKEN) MATCHT(16, &FOLLOW_16_in_atom156);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_expr_in_atom159);
        	        expr12=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, expr12.tree);

        	        char_literal13 = (pANTLR3_COMMON_TOKEN) MATCHT(17, &FOLLOW_17_in_atom161);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruleatomEx; /* Prevent compiler warnings */
    ruleatomEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end atom */

/**
 * $ANTLR start stmt
 * test.g:36:1: stmt : ( expr ';' NEWLINE -> expr | ID ASSIGN expr ';' NEWLINE -> ^( ASSIGN ID expr ) | ( ';' )* NEWLINE ->| def_stmt | print_stmt | blocks );
 */
static testParser_stmt_return
stmt(ptestParser ctx)
{
    testParser_stmt_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal15;
    pANTLR3_COMMON_TOKEN    NEWLINE16;
    pANTLR3_COMMON_TOKEN    ID17;
    pANTLR3_COMMON_TOKEN    ASSIGN18;
    pANTLR3_COMMON_TOKEN    char_literal20;
    pANTLR3_COMMON_TOKEN    NEWLINE21;
    pANTLR3_COMMON_TOKEN    char_literal22;
    pANTLR3_COMMON_TOKEN    NEWLINE23;
    testParser_expr_return expr14;
    #undef	RETURN_TYPE_expr14
    #define	RETURN_TYPE_expr14 testParser_expr_return

    testParser_expr_return expr19;
    #undef	RETURN_TYPE_expr19
    #define	RETURN_TYPE_expr19 testParser_expr_return

    testParser_def_stmt_return def_stmt24;
    #undef	RETURN_TYPE_def_stmt24
    #define	RETURN_TYPE_def_stmt24 testParser_def_stmt_return

    testParser_print_stmt_return print_stmt25;
    #undef	RETURN_TYPE_print_stmt25
    #define	RETURN_TYPE_print_stmt25 testParser_print_stmt_return

    testParser_blocks_return blocks26;
    #undef	RETURN_TYPE_blocks26
    #define	RETURN_TYPE_blocks26 testParser_blocks_return

    pANTLR3_BASE_TREE char_literal15_tree;
    pANTLR3_BASE_TREE NEWLINE16_tree;
    pANTLR3_BASE_TREE ID17_tree;
    pANTLR3_BASE_TREE ASSIGN18_tree;
    pANTLR3_BASE_TREE char_literal20_tree;
    pANTLR3_BASE_TREE NEWLINE21_tree;
    pANTLR3_BASE_TREE char_literal22_tree;
    pANTLR3_BASE_TREE NEWLINE23_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_NEWLINE;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_19;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_ID;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_ASSIGN;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_expr;
    /* Initialize rule variables
     */

    root_0 = NULL;

    char_literal15       = NULL;
    NEWLINE16       = NULL;
    ID17       = NULL;
    ASSIGN18       = NULL;
    char_literal20       = NULL;
    NEWLINE21       = NULL;
    char_literal22       = NULL;
    NEWLINE23       = NULL;
    expr14.tree = NULL;

    expr19.tree = NULL;

    def_stmt24.tree = NULL;

    print_stmt25.tree = NULL;

    blocks26.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    char_literal15_tree   = NULL;
    NEWLINE16_tree   = NULL;
    ID17_tree   = NULL;
    ASSIGN18_tree   = NULL;
    char_literal20_tree   = NULL;
    NEWLINE21_tree   = NULL;
    char_literal22_tree   = NULL;
    NEWLINE23_tree   = NULL;

    stream_NEWLINE   = NULL;
    #define CREATE_stream_NEWLINE  if (stream_NEWLINE == NULL) {stream_NEWLINE = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token NEWLINE"); } 
    stream_19   = NULL;
    #define CREATE_stream_19  if (stream_19 == NULL) {stream_19 = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token 19"); } 
    stream_ID   = NULL;
    #define CREATE_stream_ID  if (stream_ID == NULL) {stream_ID = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token ID"); } 
    stream_ASSIGN   = NULL;
    #define CREATE_stream_ASSIGN  if (stream_ASSIGN == NULL) {stream_ASSIGN = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token ASSIGN"); } 
    stream_expr   = NULL;
    #define CREATE_stream_expr  if (stream_expr == NULL) {stream_expr = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule expr"); }

    retval.tree  = NULL;

    {
        {
            //  test.g:36:5: ( expr ';' NEWLINE -> expr | ID ASSIGN expr ';' NEWLINE -> ^( ASSIGN ID expr ) | ( ';' )* NEWLINE ->| def_stmt | print_stmt | blocks )

            ANTLR3_UINT32 alt7;

            alt7=6;

            switch ( LA(1) )
            {
            case INT:
            case 16:
            	{
            		alt7=1;
            	}
                break;
            case ID:
            	{
            		switch ( LA(2) )
            		{
            		case ASSIGN:
            			{
            				alt7=2;
            			}
            		    break;
            		case DIV:
            		case MINUS:
            		case PLUS:
            		case TIMES:
            		case 19:
            			{
            				alt7=1;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 7;
            		    EXCEPTION->state        = 2;


            		    goto rulestmtEx;

            		}

            	}
                break;
            case NEWLINE:
            case 19:
            	{
            		alt7=3;
            	}
                break;
            case DEF:
            	{
            		alt7=4;
            	}
                break;
            case PRINT:
            	{
            		alt7=5;
            	}
                break;
            case 20:
            	{
            		alt7=6;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 7;
                EXCEPTION->state        = 0;


                goto rulestmtEx;

            }

            switch (alt7)
            {
        	case 1:
        	    // test.g:36:7: expr ';' NEWLINE
        	    {
        	        FOLLOWPUSH(FOLLOW_expr_in_stmt181);
        	        expr14=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }

        	        CREATE_stream_expr; stream_expr->add(stream_expr, expr14.tree, NULL);

        	        char_literal15 = (pANTLR3_COMMON_TOKEN) MATCHT(19, &FOLLOW_19_in_stmt183);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_19; stream_19->add(stream_19, char_literal15, NULL);


        	        NEWLINE16 = (pANTLR3_COMMON_TOKEN) MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_stmt185);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_NEWLINE; stream_NEWLINE->add(stream_NEWLINE, NEWLINE16, NULL);


        	        /* AST REWRITE
        	         * elements          : expr
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 36:24: -> expr
        	        	{
        	        	    ADAPTOR->addChild(ADAPTOR, root_0, stream_expr == NULL ? NULL : stream_expr->nextTree(stream_expr));

        	        	}


        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 2:
        	    // test.g:37:7: ID ASSIGN expr ';' NEWLINE
        	    {
        	        ID17 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_stmt198);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_ID; stream_ID->add(stream_ID, ID17, NULL);


        	        ASSIGN18 = (pANTLR3_COMMON_TOKEN) MATCHT(ASSIGN, &FOLLOW_ASSIGN_in_stmt200);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_ASSIGN; stream_ASSIGN->add(stream_ASSIGN, ASSIGN18, NULL);


        	        FOLLOWPUSH(FOLLOW_expr_in_stmt202);
        	        expr19=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }

        	        CREATE_stream_expr; stream_expr->add(stream_expr, expr19.tree, NULL);

        	        char_literal20 = (pANTLR3_COMMON_TOKEN) MATCHT(19, &FOLLOW_19_in_stmt204);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_19; stream_19->add(stream_19, char_literal20, NULL);


        	        NEWLINE21 = (pANTLR3_COMMON_TOKEN) MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_stmt206);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_NEWLINE; stream_NEWLINE->add(stream_NEWLINE, NEWLINE21, NULL);


        	        /* AST REWRITE
        	         * elements          : ID, ASSIGN, expr
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 37:34: -> ^( ASSIGN ID expr )
        	        	{
        	        	    // test.g:37:37: ^( ASSIGN ID expr )
        	        	    {
        	        	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, 
        	        	        stream_ASSIGN == NULL ? NULL : stream_ASSIGN->nextNode(stream_ASSIGN)
        	        	        , root_1));

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, 
        	        	        stream_ID == NULL ? NULL : stream_ID->nextNode(stream_ID)
        	        	        );

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, stream_expr == NULL ? NULL : stream_expr->nextTree(stream_expr));

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
        	        	    }

        	        	}


        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 3:
        	    // test.g:38:7: ( ';' )* NEWLINE
        	    {
        	        // test.g:38:7: ( ';' )*

        	        for (;;)
        	        {
        	            int alt6=2;
        	            switch ( LA(1) )
        	            {
        	            case 19:
        	            	{
        	            		alt6=1;
        	            	}
        	                break;

        	            }

        	            switch (alt6)
        	            {
        	        	case 1:
        	        	    // test.g:38:7: ';'
        	        	    {
        	        	        char_literal22 = (pANTLR3_COMMON_TOKEN) MATCHT(19, &FOLLOW_19_in_stmt224);
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto rulestmtEx;
        	        	        }
        	        	         
        	        	        CREATE_stream_19; stream_19->add(stream_19, char_literal22, NULL);


        	        	    }
        	        	    break;

        	        	default:
        	        	    goto loop6;	/* break out of the loop */
        	        	    break;
        	            }
        	        }
        	        loop6: ; /* Jump out to here if this rule does not match */


        	        NEWLINE23 = (pANTLR3_COMMON_TOKEN) MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_stmt227);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_NEWLINE; stream_NEWLINE->add(stream_NEWLINE, NEWLINE23, NULL);


        	        /* AST REWRITE
        	         * elements          : 
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 38:20: ->
        	        	{
        	        	    root_0 = NULL; /* <-- rewriteEmptyAlt()) */
        	        	}


        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 4:
        	    // test.g:39:7: def_stmt
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        FOLLOWPUSH(FOLLOW_def_stmt_in_stmt238);
        	        def_stmt24=def_stmt(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, def_stmt24.tree);

        	    }
        	    break;
        	case 5:
        	    // test.g:40:7: print_stmt
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        FOLLOWPUSH(FOLLOW_print_stmt_in_stmt246);
        	        print_stmt25=print_stmt(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, print_stmt25.tree);

        	    }
        	    break;
        	case 6:
        	    // test.g:41:7: blocks
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        FOLLOWPUSH(FOLLOW_blocks_in_stmt254);
        	        blocks26=blocks(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, blocks26.tree);

        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto rulestmtEx; /* Prevent compiler warnings */
    rulestmtEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_NEWLINE != NULL) stream_NEWLINE->free(stream_NEWLINE);
        if (stream_19 != NULL) stream_19->free(stream_19);
        if (stream_ID != NULL) stream_ID->free(stream_ID);
        if (stream_ASSIGN != NULL) stream_ASSIGN->free(stream_ASSIGN);
        if (stream_expr != NULL) stream_expr->free(stream_expr);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end stmt */

/**
 * $ANTLR start print_stmt
 * test.g:44:1: print_stmt : PRINT ^ expr ';' !;
 */
static testParser_print_stmt_return
print_stmt(ptestParser ctx)
{
    testParser_print_stmt_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    PRINT27;
    pANTLR3_COMMON_TOKEN    char_literal29;
    testParser_expr_return expr28;
    #undef	RETURN_TYPE_expr28
    #define	RETURN_TYPE_expr28 testParser_expr_return

    pANTLR3_BASE_TREE PRINT27_tree;
    pANTLR3_BASE_TREE char_literal29_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    PRINT27       = NULL;
    char_literal29       = NULL;
    expr28.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    PRINT27_tree   = NULL;
    char_literal29_tree   = NULL;


    retval.tree  = NULL;

    {
        // test.g:44:11: ( PRINT ^ expr ';' !)
        // test.g:44:13: PRINT ^ expr ';' !
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            PRINT27 = (pANTLR3_COMMON_TOKEN) MATCHT(PRINT, &FOLLOW_PRINT_in_print_stmt266);
            if  (HASEXCEPTION())
            {
                goto ruleprint_stmtEx;
            }

            PRINT27_tree = 
            (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, PRINT27))
            ;
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, PRINT27_tree, root_0));


            FOLLOWPUSH(FOLLOW_expr_in_print_stmt269);
            expr28=expr(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleprint_stmtEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, expr28.tree);

            char_literal29 = (pANTLR3_COMMON_TOKEN) MATCHT(19, &FOLLOW_19_in_print_stmt271);
            if  (HASEXCEPTION())
            {
                goto ruleprint_stmtEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleprint_stmtEx; /* Prevent compiler warnings */
    ruleprint_stmtEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end print_stmt */

/**
 * $ANTLR start def_stmt
 * test.g:45:1: def_stmt : DEF ^ def_id ( ',' ! def_id )* ';' !;
 */
static testParser_def_stmt_return
def_stmt(ptestParser ctx)
{
    testParser_def_stmt_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    DEF30;
    pANTLR3_COMMON_TOKEN    char_literal32;
    pANTLR3_COMMON_TOKEN    char_literal34;
    testParser_def_id_return def_id31;
    #undef	RETURN_TYPE_def_id31
    #define	RETURN_TYPE_def_id31 testParser_def_id_return

    testParser_def_id_return def_id33;
    #undef	RETURN_TYPE_def_id33
    #define	RETURN_TYPE_def_id33 testParser_def_id_return

    pANTLR3_BASE_TREE DEF30_tree;
    pANTLR3_BASE_TREE char_literal32_tree;
    pANTLR3_BASE_TREE char_literal34_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    DEF30       = NULL;
    char_literal32       = NULL;
    char_literal34       = NULL;
    def_id31.tree = NULL;

    def_id33.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    DEF30_tree   = NULL;
    char_literal32_tree   = NULL;
    char_literal34_tree   = NULL;


    retval.tree  = NULL;

    {
        // test.g:45:9: ( DEF ^ def_id ( ',' ! def_id )* ';' !)
        // test.g:45:11: DEF ^ def_id ( ',' ! def_id )* ';' !
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            DEF30 = (pANTLR3_COMMON_TOKEN) MATCHT(DEF, &FOLLOW_DEF_in_def_stmt278);
            if  (HASEXCEPTION())
            {
                goto ruledef_stmtEx;
            }

            DEF30_tree = 
            (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, DEF30))
            ;
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, DEF30_tree, root_0));


            FOLLOWPUSH(FOLLOW_def_id_in_def_stmt281);
            def_id31=def_id(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruledef_stmtEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, def_id31.tree);

            // test.g:45:23: ( ',' ! def_id )*

            for (;;)
            {
                int alt8=2;
                switch ( LA(1) )
                {
                case 18:
                	{
                		alt8=1;
                	}
                    break;

                }

                switch (alt8)
                {
            	case 1:
            	    // test.g:45:24: ',' ! def_id
            	    {
            	        char_literal32 = (pANTLR3_COMMON_TOKEN) MATCHT(18, &FOLLOW_18_in_def_stmt284);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruledef_stmtEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_def_id_in_def_stmt287);
            	        def_id33=def_id(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruledef_stmtEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, def_id33.tree);

            	    }
            	    break;

            	default:
            	    goto loop8;	/* break out of the loop */
            	    break;
                }
            }
            loop8: ; /* Jump out to here if this rule does not match */


            char_literal34 = (pANTLR3_COMMON_TOKEN) MATCHT(19, &FOLLOW_19_in_def_stmt291);
            if  (HASEXCEPTION())
            {
                goto ruledef_stmtEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruledef_stmtEx; /* Prevent compiler warnings */
    ruledef_stmtEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end def_stmt */

/**
 * $ANTLR start def_id
 * test.g:46:1: def_id : ID ^ ( ASSIGN ! expr )? ;
 */
static testParser_def_id_return
def_id(ptestParser ctx)
{
    testParser_def_id_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    ID35;
    pANTLR3_COMMON_TOKEN    ASSIGN36;
    testParser_expr_return expr37;
    #undef	RETURN_TYPE_expr37
    #define	RETURN_TYPE_expr37 testParser_expr_return

    pANTLR3_BASE_TREE ID35_tree;
    pANTLR3_BASE_TREE ASSIGN36_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    ID35       = NULL;
    ASSIGN36       = NULL;
    expr37.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    ID35_tree   = NULL;
    ASSIGN36_tree   = NULL;


    retval.tree  = NULL;

    {
        // test.g:46:7: ( ID ^ ( ASSIGN ! expr )? )
        // test.g:46:9: ID ^ ( ASSIGN ! expr )?
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            ID35 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_def_id298);
            if  (HASEXCEPTION())
            {
                goto ruledef_idEx;
            }

            ID35_tree = 
            (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, ID35))
            ;
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, ID35_tree, root_0));


            // test.g:46:13: ( ASSIGN ! expr )?
            {
                int alt9=2;
                switch ( LA(1) )
                {
                    case ASSIGN:
                    	{
                    		alt9=1;
                    	}
                        break;
                }

                switch (alt9)
                {
            	case 1:
            	    // test.g:46:14: ASSIGN ! expr
            	    {
            	        ASSIGN36 = (pANTLR3_COMMON_TOKEN) MATCHT(ASSIGN, &FOLLOW_ASSIGN_in_def_id302);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruledef_idEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_expr_in_def_id305);
            	        expr37=expr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruledef_idEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, expr37.tree);

            	    }
            	    break;

                }
            }

        }

    }

    // This is where rules clean up and exit
    //
    goto ruledef_idEx; /* Prevent compiler warnings */
    ruledef_idEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end def_id */

/**
 * $ANTLR start block_code
 * test.g:50:1: block_code : ( stmt )* ;
 */
static testParser_block_code_return
block_code(ptestParser ctx)
{
    testParser_block_code_return retval;


    pANTLR3_BASE_TREE root_0;

    testParser_stmt_return stmt38;
    #undef	RETURN_TYPE_stmt38
    #define	RETURN_TYPE_stmt38 testParser_stmt_return


    /* Initialize rule variables
     */

    root_0 = NULL;

    stmt38.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;




    retval.tree  = NULL;

    {
        // test.g:50:12: ( ( stmt )* )
        // test.g:50:14: ( stmt )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // test.g:50:14: ( stmt )*

            for (;;)
            {
                int alt10=2;
                switch ( LA(1) )
                {
                case DEF:
                case ID:
                case INT:
                case NEWLINE:
                case PRINT:
                case 16:
                case 19:
                case 20:
                	{
                		alt10=1;
                	}
                    break;

                }

                switch (alt10)
                {
            	case 1:
            	    // test.g:50:14: stmt
            	    {
            	        FOLLOWPUSH(FOLLOW_stmt_in_block_code327);
            	        stmt38=stmt(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleblock_codeEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, stmt38.tree);

            	    }
            	    break;

            	default:
            	    goto loop10;	/* break out of the loop */
            	    break;
                }
            }
            loop10: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleblock_codeEx; /* Prevent compiler warnings */
    ruleblock_codeEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end block_code */

/**
 * $ANTLR start blocks
 * test.g:51:1: blocks : '{' block_code '}' -> ^( BLOCK block_code ) ;
 */
static testParser_blocks_return
blocks(ptestParser ctx)
{
    testParser_blocks_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal39;
    pANTLR3_COMMON_TOKEN    char_literal41;
    testParser_block_code_return block_code40;
    #undef	RETURN_TYPE_block_code40
    #define	RETURN_TYPE_block_code40 testParser_block_code_return

    pANTLR3_BASE_TREE char_literal39_tree;
    pANTLR3_BASE_TREE char_literal41_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_20;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_21;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_block_code;
    /* Initialize rule variables
     */

    root_0 = NULL;

    char_literal39       = NULL;
    char_literal41       = NULL;
    block_code40.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    char_literal39_tree   = NULL;
    char_literal41_tree   = NULL;

    stream_20   = NULL;
    #define CREATE_stream_20  if (stream_20 == NULL) {stream_20 = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token 20"); } 
    stream_21   = NULL;
    #define CREATE_stream_21  if (stream_21 == NULL) {stream_21 = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token 21"); } 
    stream_block_code   = NULL;
    #define CREATE_stream_block_code  if (stream_block_code == NULL) {stream_block_code = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule block_code"); }

    retval.tree  = NULL;

    {
        // test.g:51:8: ( '{' block_code '}' -> ^( BLOCK block_code ) )
        // test.g:51:10: '{' block_code '}'
        {
            char_literal39 = (pANTLR3_COMMON_TOKEN) MATCHT(20, &FOLLOW_20_in_blocks335);
            if  (HASEXCEPTION())
            {
                goto ruleblocksEx;
            }
             
            CREATE_stream_20; stream_20->add(stream_20, char_literal39, NULL);


            FOLLOWPUSH(FOLLOW_block_code_in_blocks337);
            block_code40=block_code(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleblocksEx;
            }

            CREATE_stream_block_code; stream_block_code->add(stream_block_code, block_code40.tree, NULL);

            char_literal41 = (pANTLR3_COMMON_TOKEN) MATCHT(21, &FOLLOW_21_in_blocks339);
            if  (HASEXCEPTION())
            {
                goto ruleblocksEx;
            }
             
            CREATE_stream_21; stream_21->add(stream_21, char_literal41, NULL);


            /* AST REWRITE
             * elements          : block_code
             * token labels      : 
             * rule labels       : retval
             * token list labels : 
             * rule list labels  : 
             */
            {
            	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

            	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

            	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	retval.tree    = root_0;
            	// 51:29: -> ^( BLOCK block_code )
            	{
            	    // test.g:51:32: ^( BLOCK block_code )
            	    {
            	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, 
            	        (pANTLR3_BASE_TREE)ADAPTOR->createTypeText(ADAPTOR, BLOCK, (pANTLR3_UINT8)"BLOCK")
            	        , root_1));

            	        ADAPTOR->addChild(ADAPTOR, root_1, stream_block_code == NULL ? NULL : stream_block_code->nextTree(stream_block_code));

            	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
            	    }

            	}


            	retval.tree = root_0; // set result root
            	if (stream_retval != NULL) stream_retval->free(stream_retval);


            }
        }

    }

    // This is where rules clean up and exit
    //
    goto ruleblocksEx; /* Prevent compiler warnings */
    ruleblocksEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_20 != NULL) stream_20->free(stream_20);
        if (stream_21 != NULL) stream_21->free(stream_21);
        if (stream_block_code != NULL) stream_block_code->free(stream_block_code);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end blocks */

/**
 * $ANTLR start prog
 * test.g:55:1: prog : ( blocks )+ ;
 */
static testParser_prog_return
prog(ptestParser ctx)
{
    testParser_prog_return retval;


    pANTLR3_BASE_TREE root_0;

    testParser_blocks_return blocks42;
    #undef	RETURN_TYPE_blocks42
    #define	RETURN_TYPE_blocks42 testParser_blocks_return


    /* Initialize rule variables
     */

    root_0 = NULL;

    blocks42.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;




    retval.tree  = NULL;

    {
        // test.g:56:5: ( ( blocks )+ )
        // test.g:56:7: ( blocks )+
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // test.g:56:7: ( blocks )+
            {
                int cnt11=0;

                for (;;)
                {
                    int alt11=2;
            	switch ( LA(1) )
            	{
            	case 20:
            		{
            			alt11=1;
            		}
            	    break;

            	}

            	switch (alt11)
            	{
            	    case 1:
            	        // test.g:56:9: blocks
            	        {
            	            FOLLOWPUSH(FOLLOW_blocks_in_prog368);
            	            blocks42=blocks(ctx);

            	            FOLLOWPOP();
            	            if  (HASEXCEPTION())
            	            {
            	                goto ruleprogEx;
            	            }

            	            ADAPTOR->addChild(ADAPTOR, root_0, blocks42.tree);

            	            {

            	                            pANTLR3_STRING s = (blocks42.tree)->toStringTree((blocks42.tree));
            	                            assert(s->chars);
            	                            printf("haizei tree %s\n", s->chars);
            	                       
            	            }


            	        }
            	        break;

            	    default:

            		if ( cnt11 >= 1 )
            		{
            		    goto loop11;
            		}
            		/* mismatchedSetEx()
            		 */
            		CONSTRUCTEX();
            		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
            		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


            		goto ruleprogEx;
            	}
            	cnt11++;
                }
                loop11: ;	/* Jump to here if this rule does not match */
            }

        }

    }

    // This is where rules clean up and exit
    //
    goto ruleprogEx; /* Prevent compiler warnings */
    ruleprogEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end prog */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
